#!/usr/bin/env sh
# -*- mode: scheme; -*-
exec guile --no-auto-compile -e main -s "$0" "$@"
!#
;;; ccwl --- Concise Common Workflow Language
;;; Copyright © 2021–2026 Arun Isaac <arunisaac@systemreboot.net>
;;;
;;; This file is part of ccwl.
;;;
;;; ccwl is free software: you can redistribute it and/or modify it
;;; under the terms of the GNU General Public License as published by
;;; the Free Software Foundation, either version 3 of the License, or
;;; (at your option) any later version.
;;;
;;; ccwl is distributed in the hope that it will be useful, but
;;; WITHOUT ANY WARRANTY; without even the implied warranty of
;;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
;;; General Public License for more details.
;;;
;;; You should have received a copy of the GNU General Public License
;;; along with ccwl.  If not, see <https://www.gnu.org/licenses/>.

;;; Commentary:

;; This script is the command-line interface to ccwl.

;;; Code:

(use-modules (rnrs conditions)
             (rnrs exceptions)
             (srfi srfi-26)
             (srfi srfi-28)
             (srfi srfi-37)
             (ice-9 match)
             (ice-9 exceptions)
             (ccwl ccwl)
             (ccwl conditions)
             (ccwl cwl)
             (ccwl graphviz)
             (ccwl ui)
             (ccwl utils))

(define (invalid-option opt name arg result)
  (error "Invalid option" name))

(define %help-option
  (option (list #\h "help") #f #f
          (lambda (opt name arg result)
            (acons 'help #t result))))

(define %options
  (list (option (list #\t "to") #t #f
                (lambda (opt name arg result)
                  (let ((supported (list "cwl" "dot")))
                    (unless (member arg supported)
                      (raise-exception
                       (formatted-message "Invalid target ~a argument ~s. Supported targets are ~a."
                                          (if (char? name)
                                              (string #\- name)
                                              (string-append "--" name))
                                          arg
                                          (string-join supported ", ")))))
                  (acons 'to (string->symbol arg)
                         result)))
        (option (list #\o "output") #t #f
                (lambda (opt name arg result)
                  (acons 'output-file arg result)))
        %help-option))

(define* (ccwl-read #:optional (port (current-input-port)))
  "Read an S-expression from @var{port}. This function wraps
@code{read-syntax} to raise read errors the way ccwl likes to handle
it."
  (guard (c ((and (eq? (exception-kind c)
                       'read-error)
                  (message-condition? c)
                  (irritants-condition? c))
             ;; TODO: Once https://codeberg.org/guile/guile/issues/206
             ;; is fixed, report error in source context using
             ;; report-ccwl-violation.
             (raise-exception
              (apply formatted-message
                     (condition-message c)
                     (condition-irritants c)))))
    (read-syntax port)))

(define (ccwl-compile source to port)
  "Compile @var{source} file to @var{to} format writing output to
@var{port}. @var{to} is either @code{'cwl} or @code{'dot}."
  ;; We don't need to compile ccwl files. Loading is sufficient for
  ;; our purposes. Besides, compiling would fail since the workflow
  ;; macro cannot access command definitions.
  (set! %load-should-auto-compile #f)
  (unless (file-exists? source)
    (raise-exception
     (formatted-message "File ~a does not exist"
                        source)))
  ((case to
     ((cwl) function->cwl)
     ((dot) function->dot))
   (let ((result (guard (exception
                         ;; Handle syntax violation exceptions by
                         ;; reporting them and exiting.
                         ((ccwl-violation? exception)
                          (report-ccwl-violation exception)
                          (exit #f)))
                   (let ((source-path (canonicalize-path source)))
                     ;; Change directory before loading source file.
                     ;; The source file may reference other files with
                     ;; paths relative to its directory.
                     (call-with-current-directory (dirname source-path)
                       (lambda ()
                         (load source-path
                               ccwl-read)))))))
     (if (or (command? result)
             (js-expression? result)
             (workflow? result))
         result
         (raise-exception
          (formatted-message "Last expression in file ~a returns none of workflow, command or js-expression"
                             source))))
   port))

(define (main args)
  (with-exception-handler
      (lambda (condition)
        ;; Catch uncaught exceptions, request the user report an
        ;; issue, and re-raise the exception so the default exception
        ;; handler can deal with it. Pass quit exceptions through
        ;; since those may be raised by exceptions that have been
        ;; handled.
        (cond
         ((formatted-message? condition)
          (report-formatted-message condition))
         ((not (quit-exception? condition))
          (display "You have discovered a bug! ccwl crashed! :-(
Please report this to ccwl@systemreboot.net
Thank you!\n\n"
                   (current-error-port))
          (write condition (current-error-port))
          (newline (current-error-port))
          (newline (current-error-port))
          (raise-exception condition)))
        (exit #f))
    (lambda ()
      (match args
        ((program "compile" args ...)
         (let ((args (args-fold args
                                %options
                                invalid-option
                                (lambda (arg result)
                                  (acons 'source-file arg result))
                                '((to . cwl)))))
           (when (or (assq 'help args)
                     (not (assq-ref args 'source-file)))
             (display (format "Usage: ~a compile [OPTIONS] SOURCE-FILE
Compile SOURCE-FILE.

  -o, --output=FILE  write compiled output to file
  -t, --to=TARGET    compile SOURCE-FILE to TARGET language;
                     Supported targets are cwl (default) and dot.
  --help             display this help and exit
"
                              program)
                      (current-error-port))
             (exit (assq 'help args)))
           (if (assq-ref args 'output-file)
               (call-with-output-file (assq-ref args 'output-file)
                 (cut ccwl-compile
                      (assq-ref args 'source-file)
                      (assq-ref args 'to)
                      <>))
               (ccwl-compile (assq-ref args 'source-file)
                             (assq-ref args 'to)
                             (current-output-port)))))
        ((program args ...)
         (let ((args (args-fold args
                                (list %help-option)
                                (lambda (opt name arg result)
                                  result)
                                (lambda (arg result)
                                  result)
                                '())))
           (display (format "Usage: ~a COMMAND [OPTIONS] [ARGS]

COMMAND must be one of the sub-commands listed below:

  compile   compile a workflow

To get usage information for one of these sub-commands, run
  ~a COMMAND --help

"
                            program program)
                    (current-error-port))
           (exit (assq 'help args))))))))
